apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    app: mysql
    project: expense
    teir: database
spec:
  clusterIP: None
  selector:
    app: mysql
    project: expense
    teir: database
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
    teir: database
spec:
  selector:
    app: mysql
    project: expense
    teir: database
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306
