
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      app: mysql  # has to match .spec.template.metadata.labels
      project: expense
      teir: database
  serviceName: "mysql-headless"
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        teir: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: parthureddy3/mysql:{{ .Values.statefulset.imageVersion }}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # instead of creating seperate resource for pvc, you do it by using volumeClaimTemplate
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: expense
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}