apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec: 
  selector:   # lables are used as selectors 
    app: backend
    teir: backend
    project: expense
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080